// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlo59MrKvRo2pTXZ777W3FzGsejee_Z0Y',
    appId: '1:834864364850:web:f1e468a0b9815734766b2b',
    messagingSenderId: '834864364850',
    projectId: 'dzikir-app-dev',
    authDomain: 'dzikir-app-dev.firebaseapp.com',
    storageBucket: 'dzikir-app-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxcVHqSfrbWMGZ03fHCXbkWYHzD0uL_Y',
    appId: '1:834864364850:android:21ef0924008b8f13766b2b',
    messagingSenderId: '834864364850',
    projectId: 'dzikir-app-dev',
    storageBucket: 'dzikir-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedrDTDoPbjcWvoCkBlaQDu9p8jKQ58QI',
    appId: '1:834864364850:ios:c4e9876febfd89fa766b2b',
    messagingSenderId: '834864364850',
    projectId: 'dzikir-app-dev',
    storageBucket: 'dzikir-app-dev.appspot.com',
    iosBundleId: 'com.example.dzikirapp',
  );
}
